[package]
name = "lrclib-challenger"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { version = "23.0.1", features = ["spirv"] }
tokio = { version = "*", features = ["full"] }
bytemuck = "1.21.0"
futures-intrusive = "0.5.0"
gpu-compute = { path = "./crates/wgpu-compute/" }
hex = "0.4.3"
